version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
        - mongo-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "16000:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
    networks:
        - mongo-network

networks:
    mongo-network:
        driver: bridge